[tool.bumpversion]
current_version = "1.0.1.4"
commit = true
commit_args = "--no-verify"
tag = true
tag_name = "v{new_version}"
allow_dirty = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<build>\\d+))?"
serialize = ["{major}.{minor}.{patch}.{build}", "{major}.{minor}.{patch}"]
message = "Version updated from {current_version} to {new_version}"
