version: '3'

tasks:
  init:
    cmds:
      - echo "Initializing project..."
      - uv venv --clear
      - uv pip install -r requirements.txt
      - pre-commit autoupdate
      - pre-commit install
      - pre-commit run -a
  bump:
    vars:
      PART: '{{ .PART | default "build"}}'
    cmds:
      - bump-my-version bump {{ .PART }}
  devrel:
    cmds:
      - git add .
      - if git commit --dry-run --short; then git commit -m "devrel"; else echo nothing changed; fi
      - task: bump
      - git push --follow-tags
  release:
    cmds:
      - task: bump
        vars:
          PART: 'patch'
      - git push --follow-tags
      - echo "Creating GitHub release..."
      - bump-my-version show scm_info.current_tag
      - gh release create $(bump-my-version show scm_info.current_tag) --generate-notes
