version: '3'

tasks:
  init:
    cmds:
      - echo "Initializing project..."
      - uv venv --clear
      - uv pip install -r requirements.txt
      - pre-commit autoupdate
      - pre-commit install
      - pre-commit run -a
  bump:
    vars:
      PART: '{{ .PART | default "build"}}'
    cmds:
      - bump-my-version bump {{ .PART }}
  devrel:
    deps: [bump]
    cmds:
      - git push --follow-tags
